### ISSUE TITLE
Update Ubuntu build directions?

### ISSUE THREAD

**Issue by chimaerase** [hank-ai/darknet#74] opened 2024-08-09 17:55 UTC
I had trouble building Darknet on my system according to the directions..it appears that they need an update to save others from going through a similar process.

TLDR: changes I think are needed in the [Ubuntu build directions](https://github.com/hank-ai/darknet?tab=readme-ov-file#linux-cmake-method) + maybe the build configuration:
1. Document that the `file` package needs to be installed via `apt-get`
2. Update docs to use the `build_ubuntu.sh`  script
3. Maybe check for the `file` package in the build (seems many similar checks already exist)

EDIT: I now realize my initial report was due to issues in v3.0.0..making some updates here but I hope at least part of my comments may still be helpful.

-------

<ins>Context for the test</ins>: For now, I'm working on an M2 Macbook (Sonoma) and experimenting in a custom Dockerfile based on `nvidia/cuda:12.5.1-cudnn-runtime-ubuntu22.04`.  Yes, I know CUDA won't work on my Mac..I'm just testing out my Dockerfile locally first.  Trying to build Darknet from `master`

I initially tripped over problems running this command against the Darknet `v3.0` tag.  
```
-- Darknet v3.0
CMake Error at CMakeLists.txt:28 (PROJECT):
  VERSION ".." format invalid.
```

After switching to `master` and poking around, I found that there was a different way to do the build using `build_ubuntu.sh` that mostly worked, but failed at the end:
```
# ./build_ubuntu.sh
... [lots of output]
Run CPack packaging tool...
/usr/bin/cpack --config ./CPackConfig.cmake
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: Darknet
CPack: - Install project: Darknet []
CPack: Create package
CMake Error at /usr/share/cmake-3.30/Modules/Internal/CPack/CPackDeb.cmake:224 (message):
  CPackDeb: file utility is not available.  CPACK_DEBIAN_PACKAGE_SHLIBDEPS
  and CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS options are not available.
Call Stack (most recent call first):
  /usr/share/cmake-3.30/Modules/Internal/CPack/CPackDeb.cmake:888 (cpack_deb_prepare_package_vars)


CPack Error: Error while execution CPackDeb.cmake
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: darknet
make: *** [Makefile:74: package] Error 1
```

After searching around, I found that the `file` utility (not mentioned in the directions) wasn't installed on my system, so I added it and that seemed to work.

```
# apt-get install file
[lots of output]
./build_ubuntu.sh
[lots of output]
Run CPack packaging tool...
/usr/bin/cpack --config ./CPackConfig.cmake
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: Darknet
CPack: - Install project: Darknet []
CPack: Create package
CPackDeb: - Generating dependency list
CPack: - package: /usr/local/yolo-test/src/darknet/build/darknet-2.0.226-Linux.deb generated.
Done!
Make sure you install the .deb file:
-rw-r--r-- 1 root root 1.4M Aug  9 17:52 darknet-2.0.226-Linux.deb
```

**Comment by stephanecharette** [comment] 2024-08-10 20:58
Closing since v3 is in development and shouldn't be used by anyone other than dev.

The instructions have been confirmed thousands of times to work well in a stock Ubuntu installation.  I have also uploaded to youtube a video showing step-by-step the build and installation of Darknet on Ubuntu.  I recommend you follow that video to see everything that is required.  Note that the old "build_ubuntu.sh" script does exactly what the readme and the youtube video recommends, it doesn't do anything special.  Look at the contents if you're curious, it is only a few lines long, of which about 3 lines are actually relevant.

If you're not using a normal recent Ubuntu installation, then you'll of course have to modify the instructions, but this is to be expected, and advanced users are doing custom solutions are expected to know what they need to modify.  Sounds like this is the case since you're using a combination of Mac and Docker.

Note that Darknet/YOLO definitely does not use nor link against "file" (which is installed by default in Ubuntu).  But I wouldn't be surprised to hear that a build tool or script you are using might require it.

**Closed by stephanecharette** 2024-08-10 20:58 UTC
Labels: bug
